#!/usr/bin/env bash
# Freeflix Setup Wizard
# Usage: bash <(curl -sSL https://raw.githubusercontent.com/evilsocket/freeflix/main/wizard.sh)
set -euo pipefail

# When piped from curl, stdin is consumed — read user input from /dev/tty
exec < /dev/tty

IMAGE="ghcr.io/evilsocket/freeflix:latest"
ENV_FILE="$HOME/.freeflix/.env"

# ── Colors ──
if [ -t 1 ] && [ "${TERM:-dumb}" != "dumb" ]; then
  BOLD='\033[1m'
  DIM='\033[2m'
  CYAN='\033[36m'
  GREEN='\033[32m'
  YELLOW='\033[33m'
  RED='\033[31m'
  RESET='\033[0m'
else
  BOLD='' DIM='' CYAN='' GREEN='' YELLOW='' RED='' RESET=''
fi

header()  { echo -e "\n${BOLD}${CYAN}$1${RESET}"; }
success() { echo -e "${GREEN}$1${RESET}"; }
warn()    { echo -e "${YELLOW}$1${RESET}"; }
error()   { echo -e "${RED}$1${RESET}" >&2; }

mask() {
  local v="$1"
  local len=${#v}
  if [ "$len" -le 8 ]; then
    echo "****"
  else
    echo "${v:0:4}...${v: -4}"
  fi
}

# Prompt with optional default value
# Usage: ask "Prompt text" [default]
ask() {
  local prompt="$1"
  local default="${2:-}"
  if [ -n "$default" ]; then
    echo -en "  ${prompt} ${DIM}[${default}]${RESET}: " > /dev/tty
  else
    echo -en "  ${prompt}: " > /dev/tty
  fi
  read -r answer
  echo "${answer:-$default}"
}

ask_yn() {
  local prompt="$1"
  local default="${2:-n}"
  local hint="y/N"
  [ "$default" = "y" ] && hint="Y/n"
  echo -en "  ${prompt} ${DIM}[${hint}]${RESET}: "
  read -r answer
  answer="${answer:-$default}"
  case "$answer" in
    [yY]*) return 0 ;;
    *) return 1 ;;
  esac
}

# Build docker command from env vars
build_cmd() {
  CMD=(docker run -it --rm --name freeflix)

  [ -n "$ANTHROPIC_API_KEY" ]      && CMD+=(-e "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY")
  [ -n "$OPENAI_API_KEY" ]         && CMD+=(-e "OPENAI_API_KEY=$OPENAI_API_KEY")
  [ -n "$OPENCODE_MODEL" ]         && CMD+=(-e "OPENCODE_MODEL=$OPENCODE_MODEL")
  [ -n "$OPENCODE_API_KEY" ]       && CMD+=(-e "OPENCODE_API_KEY=$OPENCODE_API_KEY")
  [ -n "$TRAKT_CLIENT_ID" ]        && CMD+=(-e "TRAKT_CLIENT_ID=$TRAKT_CLIENT_ID")
  [ -n "$TRAKT_CLIENT_SECRET" ]    && CMD+=(-e "TRAKT_CLIENT_SECRET=$TRAKT_CLIENT_SECRET")
  [ -n "$TELEGRAM_BOT_TOKEN" ]     && CMD+=(-e "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN")
  [ -n "$TELEGRAM_ALLOWED_USERS" ] && CMD+=(-e "TELEGRAM_ALLOWED_USERS=$TELEGRAM_ALLOWED_USERS")

  CMD+=(-v "$DOWNLOADS_DIR:/downloads")
  CMD+=(-v "$HOME/.freeflix:/data")
  CMD+=("$IMAGE")
}

show_summary() {
  echo ""
  if [ -n "$ANTHROPIC_API_KEY" ]; then
    echo "  LLM Provider:    Anthropic ($(mask "$ANTHROPIC_API_KEY"))"
  elif [ -n "$OPENAI_API_KEY" ]; then
    echo "  LLM Provider:    OpenAI ($(mask "$OPENAI_API_KEY"))"
  elif [ -n "$OPENCODE_MODEL" ]; then
    echo "  LLM Provider:    $OPENCODE_MODEL"
  else
    echo "  LLM Provider:    OpenCode Zen (free)"
  fi

  if [ -n "$TRAKT_CLIENT_ID" ]; then
    echo "  Trakt:           Enabled ($(mask "$TRAKT_CLIENT_ID"))"
  else
    echo "  Trakt:           Disabled"
  fi

  if [ -n "$TELEGRAM_BOT_TOKEN" ]; then
    echo "  Telegram:        Enabled ($(mask "$TELEGRAM_BOT_TOKEN"))"
    [ -n "$TELEGRAM_ALLOWED_USERS" ] && echo "  Allowed users:   $TELEGRAM_ALLOWED_USERS"
  else
    echo "  Telegram:        Disabled"
  fi

  echo "  Downloads:       $DOWNLOADS_DIR"
  echo "  Data:            $HOME/.freeflix"
  echo ""
}

save_config() {
  mkdir -p "$(dirname "$ENV_FILE")"
  cat > "$ENV_FILE" << EOF
# Freeflix configuration — generated by wizard.sh
DOWNLOADS_DIR="$DOWNLOADS_DIR"
ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY"
OPENAI_API_KEY="$OPENAI_API_KEY"
OPENCODE_MODEL="$OPENCODE_MODEL"
OPENCODE_API_KEY="$OPENCODE_API_KEY"
TRAKT_CLIENT_ID="$TRAKT_CLIENT_ID"
TRAKT_CLIENT_SECRET="$TRAKT_CLIENT_SECRET"
TELEGRAM_BOT_TOKEN="$TELEGRAM_BOT_TOKEN"
TELEGRAM_ALLOWED_USERS="$TELEGRAM_ALLOWED_USERS"
EOF
  chmod 600 "$ENV_FILE"
}

pull_and_run() {
  header "Starting Freeflix"
  echo ""
  echo -e "  ${DIM}docker pull $IMAGE${RESET}"
  docker pull "$IMAGE"
  echo ""
  docker rm -f freeflix 2>/dev/null || true
  echo -e "  ${DIM}${CMD[*]}${RESET}"
  echo ""
  exec "${CMD[@]}"
}

install_launcher() {
  local target="$1"
  cat > "$target" << 'LAUNCHER'
#!/usr/bin/env bash
set -euo pipefail

IMAGE="ghcr.io/evilsocket/freeflix:latest"
ENV_FILE="$HOME/.freeflix/.env"

if [ ! -f "$ENV_FILE" ]; then
  echo "No config found at $ENV_FILE" >&2
  echo "Run the setup wizard first:" >&2
  echo "  bash <(curl -sSL https://raw.githubusercontent.com/evilsocket/freeflix/main/wizard.sh)" >&2
  exit 1
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

CMD=(docker run -it --rm --name freeflix)

[ -n "${ANTHROPIC_API_KEY:-}" ]      && CMD+=(-e "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY")
[ -n "${OPENAI_API_KEY:-}" ]         && CMD+=(-e "OPENAI_API_KEY=$OPENAI_API_KEY")
[ -n "${OPENCODE_MODEL:-}" ]         && CMD+=(-e "OPENCODE_MODEL=$OPENCODE_MODEL")
[ -n "${OPENCODE_API_KEY:-}" ]       && CMD+=(-e "OPENCODE_API_KEY=$OPENCODE_API_KEY")
[ -n "${TRAKT_CLIENT_ID:-}" ]        && CMD+=(-e "TRAKT_CLIENT_ID=$TRAKT_CLIENT_ID")
[ -n "${TRAKT_CLIENT_SECRET:-}" ]    && CMD+=(-e "TRAKT_CLIENT_SECRET=$TRAKT_CLIENT_SECRET")
[ -n "${TELEGRAM_BOT_TOKEN:-}" ]     && CMD+=(-e "TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN")
[ -n "${TELEGRAM_ALLOWED_USERS:-}" ] && CMD+=(-e "TELEGRAM_ALLOWED_USERS=$TELEGRAM_ALLOWED_USERS")

DOWNLOADS_DIR="${DOWNLOADS_DIR:-$(pwd)}"
CMD+=(-v "$DOWNLOADS_DIR:/downloads")
CMD+=(-v "$HOME/.freeflix:/data")
CMD+=("$IMAGE")

# Remove leftover container and pull latest
docker rm -f freeflix 2>/dev/null || true
docker pull "$IMAGE"
exec "${CMD[@]}"
LAUNCHER
  chmod +x "$target"
}

do_install_launcher() {
  if [ -d "$HOME/.local/bin" ] && echo "$PATH" | grep -q "$HOME/.local/bin"; then
    DEFAULT_DIR="$HOME/.local/bin"
  elif [ -w /usr/local/bin ]; then
    DEFAULT_DIR="/usr/local/bin"
  else
    DEFAULT_DIR="$HOME/.local/bin"
  fi

  INSTALL_DIR=$(ask "Install directory" "$DEFAULT_DIR")
  INSTALL_DIR=$(eval echo "$INSTALL_DIR")
  LAUNCHER_PATH="$INSTALL_DIR/freeflix"

  [ ! -d "$INSTALL_DIR" ] && mkdir -p "$INSTALL_DIR"

  if [ -w "$INSTALL_DIR" ]; then
    install_launcher "$LAUNCHER_PATH"
  else
    warn "  $INSTALL_DIR is not writable, using sudo..."
    TMP_LAUNCHER=$(mktemp)
    install_launcher "$TMP_LAUNCHER"
    sudo mv "$TMP_LAUNCHER" "$LAUNCHER_PATH"
    sudo chmod +x "$LAUNCHER_PATH"
  fi

  success "  Installed to $LAUNCHER_PATH"

  if ! echo "$PATH" | tr ':' '\n' | grep -qx "$INSTALL_DIR"; then
    warn "  Note: $INSTALL_DIR is not in your PATH"
    echo -e "  ${DIM}Add to your shell profile: export PATH=\"$INSTALL_DIR:\$PATH\"${RESET}"
  fi
}

# ── Welcome ──
echo ""
echo -e "${BOLD}  ___                ___ _ _      ${RESET}"
echo -e "${BOLD} |  _|_ _ ___ ___  |  _| |_|_ _  ${RESET}"
echo -e "${BOLD} |  _| '_| -_| -_| |  _| | |_'_| ${RESET}"
echo -e "${BOLD} |_| |_| |___|___| |_| |_|_|_,_| ${RESET}"
echo ""
echo -e "  ${DIM}AI-powered media discovery & download system${RESET}"
echo ""

# ── Preflight ──
header "Preflight checks"

if ! command -v docker &>/dev/null; then
  error "  Docker is not installed. Please install Docker first: https://docs.docker.com/get-docker/"
  exit 1
fi
success "  Docker found"

if ! docker info &>/dev/null; then
  error "  Docker daemon is not running. Please start Docker and try again."
  exit 1
fi
success "  Docker daemon is running"

# ── Init defaults ──
ANTHROPIC_API_KEY=""
OPENAI_API_KEY=""
OPENCODE_MODEL=""
OPENCODE_API_KEY=""
TRAKT_CLIENT_ID=""
TRAKT_CLIENT_SECRET=""
TELEGRAM_BOT_TOKEN=""
TELEGRAM_ALLOWED_USERS=""
DOWNLOADS_DIR="$(pwd)"

# ── If config exists, load and run (skip wizard) ──
if [ -f "$ENV_FILE" ]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  success "\n  Loaded config from $ENV_FILE"

  show_summary
  build_cmd

  # Offer launcher install if not already installed
  if ! command -v freeflix &>/dev/null; then
    if ask_yn "Install 'freeflix' command?" "y"; then
      do_install_launcher
    fi
  fi

  if ask_yn "Start with this config?" "y"; then
    pull_and_run
  fi

  echo ""
  warn "  Reconfiguring..."
fi

# ── LLM Provider ──
header "LLM Provider"
echo ""
echo "  1) OpenCode Zen free tier (no API key needed)"
echo "  2) Anthropic (Claude)"
echo "  3) OpenAI (GPT-4o)"
echo "  4) Custom model"
echo ""

# Detect current provider for default
DEFAULT_LLM="1"
[ -n "$ANTHROPIC_API_KEY" ] && DEFAULT_LLM="2"
[ -n "$OPENAI_API_KEY" ] && DEFAULT_LLM="3"
[ -n "$OPENCODE_MODEL" ] && [ -n "$OPENCODE_API_KEY" ] && DEFAULT_LLM="4"

while true; do
  LLM_CHOICE=$(ask "Choose provider (1-4)" "$DEFAULT_LLM")
  case "$LLM_CHOICE" in
    1|2|3|4) break ;;
    *) error "  Invalid choice: $LLM_CHOICE (enter 1-4)" ;;
  esac
done

# Reset LLM vars before setting the chosen one
ANTHROPIC_API_KEY=""
OPENAI_API_KEY=""
OPENCODE_MODEL=""
OPENCODE_API_KEY=""

case "$LLM_CHOICE" in
  2)
    ANTHROPIC_API_KEY=$(ask "Anthropic API key" "$ANTHROPIC_API_KEY")
    if [ -z "$ANTHROPIC_API_KEY" ]; then
      error "  API key is required for Anthropic"
      exit 1
    fi
    ;;
  3)
    OPENAI_API_KEY=$(ask "OpenAI API key" "$OPENAI_API_KEY")
    if [ -z "$OPENAI_API_KEY" ]; then
      error "  API key is required for OpenAI"
      exit 1
    fi
    ;;
  4)
    OPENCODE_MODEL=$(ask "Model name (provider/model)" "$OPENCODE_MODEL")
    OPENCODE_API_KEY=$(ask "API key (if needed)" "$OPENCODE_API_KEY")
    if [ -z "$OPENCODE_MODEL" ]; then
      error "  Model name is required"
      exit 1
    fi
    ;;
  *)
    # Free tier, nothing to configure
    ;;
esac

# ── Trakt ──
header "Trakt Integration"
echo -e "  ${DIM}Personalized recommendations based on your watch history.${RESET}"
echo -e "  ${DIM}Get credentials at https://trakt.tv/oauth/applications${RESET}"
echo ""

TRAKT_DEFAULT="n"
[ -n "$TRAKT_CLIENT_ID" ] && TRAKT_DEFAULT="y"

if ask_yn "Enable Trakt?" "$TRAKT_DEFAULT"; then
  TRAKT_CLIENT_ID=$(ask "Client ID" "$TRAKT_CLIENT_ID")
  TRAKT_CLIENT_SECRET=$(ask "Client Secret" "$TRAKT_CLIENT_SECRET")
  if [ -z "$TRAKT_CLIENT_ID" ] || [ -z "$TRAKT_CLIENT_SECRET" ]; then
    error "  Both Client ID and Client Secret are required"
    exit 1
  fi
else
  TRAKT_CLIENT_ID=""
  TRAKT_CLIENT_SECRET=""
fi

# ── Telegram ──
header "Telegram Bot"
echo -e "  ${DIM}Control Freeflix via Telegram messages.${RESET}"
echo -e "  ${DIM}Create a bot at https://t.me/BotFather${RESET}"
echo ""

TELEGRAM_DEFAULT="n"
[ -n "$TELEGRAM_BOT_TOKEN" ] && TELEGRAM_DEFAULT="y"

if ask_yn "Enable Telegram bot?" "$TELEGRAM_DEFAULT"; then
  TELEGRAM_BOT_TOKEN=$(ask "Bot token" "$TELEGRAM_BOT_TOKEN")
  TELEGRAM_ALLOWED_USERS=$(ask "Allowed user IDs (comma-separated)" "$TELEGRAM_ALLOWED_USERS")
  if [ -z "$TELEGRAM_BOT_TOKEN" ]; then
    error "  Bot token is required"
    exit 1
  fi
else
  TELEGRAM_BOT_TOKEN=""
  TELEGRAM_ALLOWED_USERS=""
fi

# ── Downloads ──
header "Downloads"
DOWNLOADS_DIR=$(ask "Downloads directory" "$DOWNLOADS_DIR")
DOWNLOADS_DIR=$(eval echo "$DOWNLOADS_DIR")  # expand ~ and vars

if [ ! -d "$DOWNLOADS_DIR" ]; then
  if ask_yn "  $DOWNLOADS_DIR does not exist. Create it?"; then
    mkdir -p "$DOWNLOADS_DIR"
    success "  Created $DOWNLOADS_DIR"
  else
    error "  Downloads directory must exist"
    exit 1
  fi
fi

# ── Summary ──
header "Configuration Summary"
show_summary
build_cmd

# ── Persist ──
if ask_yn "Save config to $ENV_FILE?" "y"; then
  save_config
  success "  Saved to $ENV_FILE (permissions: 600)"
fi

# ── Install launcher ──
header "Install Launcher"
echo -e "  ${DIM}Install a 'freeflix' command so you can start with just: freeflix${RESET}"
echo ""

if ask_yn "Install 'freeflix' command?" "y"; then
  do_install_launcher
fi

# ── Pull & Run ──
pull_and_run
